### ISSUE TITLE
waitFor behaviour?

### ISSUE THREAD

**Issue by jkoudys** [tc39/proposal-observable#101]
If you ever want to normalize data, or create any kind of dependency on modified data read from an observable, a `waitFor` type of method (e.g. from facebook flux's Dispatcher class) is necessary. I was reading through in the Subscription interface, and I don't see anywhere where it's used that I could implement behaviour like that.

I'm thinking something along the lines of:

```
import myObservable from './myDispatcher';
const myData = new Map([['a', 123], ['b', 456]]);

const subOne = myObservable.subscribe(({ key, value }) => {
  if (value > 5) myData.set(key, value);
});
const subTwo = myObservable.subscribe(({ key }) => {
  // Wait For the other subscription to finish the current part of the sequence.
  subOne.waitFor();
  console.log(`Val at ${key} is ${myData.get(key)}`);
});
```

In my trivial example, the order will just be the order the subscriptions are made. This breaks down when you're setting up different subscriptions in different modules and `import`ing them.

If I'm just not seeing how to do this with the current implementation, please include an example of this, since it's a common pattern I'm sure others will find useful.

**Comment by zenparsing** [comment]
@jkoudys If I understand your example correctly, you'd like to enforce some kind of event dispatch ordering among subscriptions to the same multicast observable.

First, note that this specification does not address multiple subscriptions to the same "observable" (i.e. multicast observables), although you can fairly easily define such things on top of this API.  If you'd like to attach additional behaviors to the Subscription object, you can do so by subclassing Observable and overriding the `subscribe` function to return an augmented subscription object.

I'm pretty sure that there's a different, more "Rx" way to accomplish what you want though.  @blesh , any thoughts?

**Comment by staltz** [comment]
"then" chaining in Rx can be accomplished with `flatMap` / `switchMap` / `concatMap`. "Waiting" exists in multiple operators, I think for this particular case, `combineLatest` or `zip` would have worked just fine (it doesn't matter which one since these Observables involved emit just one value anyway). However, it looks really really wrong to have two separate `myObservable.subscribe`. Probably the two concurrent tasks should have been modeled as `map` operations from `myObservable`, then combined. But still, it looks very wrong since `if (value > 5) myData.set(key, value);` is synchronous (I assume).

**Comment by jhusain** [comment]
Closing due to lack of engagement on this issue.
